version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: fundedsafe_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fundedsafe_network

  # Redis for session storage and caching
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fundedsafe_network

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/fundedsafe_db
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: your-secret-key-here
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis
    networks:
      - fundedsafe_network
    volumes:
      - .:/app
      - /app/node_modules

  # WebSocket Server
  websocket-server:
    build:
      context: .
      dockerfile: server/Dockerfile
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/fundedsafe_db
      PORT: 3001
    depends_on:
      - db
      - redis
    networks:
      - fundedsafe_network

volumes:
  postgres_data:
  redis_data:

networks:
  fundedsafe_network:
    driver: bridge